Repository DevCourse-KACG/Backend, pull requests merged in 2025-08, with the labels that each got.

#137 [Feat] 초대 링크 생성
  src/main/java/com/back/domain/club/club/controller/ApiV1ClubController.java
  src/main/java/com/back/domain/club/clubLink/controller/ApiV1ClubLinkController.java
  src/main/java/com/back/domain/club/clubLink/dtos/ClubLinkDtos.java
  src/main/java/com/back/domain/club/clubLink/entity/ClubLink.java
  src/main/java/com/back/domain/club/clubLink/repository/ClubLinkRepository.java
  src/main/java/com/back/domain/club/clubLink/service/ClubLinkService.java
  src/main/java/com/back/domain/club/clubMember/repository/ClubMemberRepository.java
  src/test/java/com/back/domain/club/clubLink/controller/ApiV1ClubLinkControllerTest.java
Labels: feat

#138 [Feat] PreAuthorize 도입 - 모임 유효성 체크, 모임장 권한 체크
  src/main/java/com/back/domain/checkList/checkList/checker/CheckListAuthorizationChecker.java
  src/main/java/com/back/domain/checkList/checkList/repository/CheckListRepository.java
  src/main/java/com/back/domain/checkList/checkList/service/CheckListService.java
  src/main/java/com/back/domain/club/club/checker/ClubAuthorizationChecker.java
  src/main/java/com/back/domain/club/club/repository/ClubRepository.java
  src/main/java/com/back/domain/club/club/service/ClubService.java
  src/main/java/com/back/domain/schedule/schedule/checker/ScheduleAuthorizationChecker.java
  src/main/java/com/back/domain/schedule/schedule/repository/ScheduleRepository.java
  src/main/java/com/back/domain/schedule/schedule/service/ScheduleService.java
  src/main/java/com/back/global/security/MockAuthFilterForSpecificApi.java
  src/main/java/com/back/global/security/SecurityConfig.java
Labels: feat

#142 [Refactor] 일정 리팩토링, 체커 헬퍼메서드 각 서비스로 위임
  src/main/java/com/back/domain/club/club/checker/ClubAuthorizationChecker.java
  src/main/java/com/back/domain/club/club/error/ClubErrorCode.java
  src/main/java/com/back/domain/club/club/service/ClubService.java
  src/main/java/com/back/domain/club/clubMember/service/ClubMemberService.java
  src/main/java/com/back/domain/member/member/service/MemberService.java
  src/main/java/com/back/domain/schedule/schedule/controller/ApiV1ScheduleController.java
  src/main/java/com/back/domain/schedule/schedule/error/ScheduleErrorCode.java
  src/main/java/com/back/domain/schedule/schedule/service/ScheduleService.java
  src/test/java/com/back/domain/schedule/schedule/controller/ApiV1ScheduleControllerTest.java
Labels: refactor

#144 [feat] 공개 모임 가입 신청
  src/main/java/com/back/domain/club/clubMember/controller/ApiV1MyClubController.java
  src/main/java/com/back/domain/club/clubMember/dtos/MyClubControllerDtos.java
  src/main/java/com/back/domain/club/clubMember/service/MyClubService.java
  src/test/java/com/back/domain/club/clubMember/controller/ApiV1MyClubControllerTest.java
Labels: feat

#146 [hotfix] 회원탈퇴 테스트 실패 수정
  src/test/java/com/back/domain/member/member/ApiV1MemberControllerTest.java
Labels: fix

#148 [fix] MockAuthFilterForSpecificApi 테스트 일때만 필터 적용
  src/main/java/com/back/global/security/SecurityConfig.java
Labels: fix

#149 [fix] 멤버 초대 시 상태에 따른 예외 처리
  src/main/java/com/back/domain/club/clubMember/repository/ClubMemberRepository.java
  src/main/java/com/back/domain/club/clubMember/service/ClubMemberService.java
  src/test/java/com/back/domain/club/clubMember/controller/ApiV1ClubMemberControllerTest.java
Labels: fix

#150 [Feat] 비공개 모임 가입 신청
  src/main/java/com/back/domain/club/clubLink/controller/ApiV1ClubLinkController.java
  src/main/java/com/back/domain/club/clubLink/entity/ClubLink.java
  src/main/java/com/back/domain/club/clubLink/repository/ClubLinkRepository.java
  src/main/java/com/back/domain/club/clubLink/service/ClubLinkService.java
  src/main/java/com/back/domain/member/member/repository/MemberRepository.java
  src/main/java/com/back/global/initData/TestInitData.java
  src/test/java/com/back/domain/club/clubLink/controller/ApiV1ClubLinkControllerTest.java
Labels: feat

#152 [feat] 모임 가입 신청 수락
  src/main/java/com/back/domain/club/club/entity/Club.java
  src/main/java/com/back/domain/club/clubMember/controller/ApiV1ClubMemberController.java
  src/main/java/com/back/domain/club/clubMember/controller/ApiV1MyClubController.java
  src/main/java/com/back/domain/club/clubMember/service/ClubMemberService.java
  src/test/java/com/back/domain/club/clubMember/controller/ApiV1ClubMemberControllerTest.java
  src/test/java/com/back/domain/club/clubMember/controller/ApiV1MyClubControllerTest.java
Labels: feat

#153 [refactor] 가입된 모임 참여자만 권한
  src/main/java/com/back/domain/club/club/checker/ClubAuthorizationChecker.java
  src/main/java/com/back/domain/club/club/service/ClubService.java
  src/main/java/com/back/domain/club/clubMember/repository/ClubMemberRepository.java
  src/main/java/com/back/domain/club/clubMember/service/ClubMemberService.java
  src/main/java/com/back/global/initData/TestInitData.java
Labels: refactor

#156 [Refactor] : ExceptionHandler 코드 추가
  src/main/java/com/back/global/globalExceptionHandler/GlobalExceptionHandler.java
Labels: refactor

#157 [Refactor] : PreAuthorize 로 변경
  src/main/java/com/back/domain/checkList/checkList/checker/CheckListAuthorizationChecker.java
  src/main/java/com/back/domain/checkList/checkList/controller/ApiV1CheckListController.java
  src/main/java/com/back/domain/checkList/checkList/service/CheckListService.java
  src/test/java/com/back/domain/checkList/ApiV1CheckListControllerTest.java
Labels: refactor

#161 [feat] 클럽 카테고리별 플랫폼 프리셋
  src/main/java/com/back/domain/preset/preset/controller/ApiV1PresetController.java
  src/main/java/com/back/domain/preset/preset/service/PresetService.java
  src/main/java/com/back/global/enums/ClubCategory.java
  src/main/resources/presets/preset-data.json
Labels: feat

#162 [refactor] 모임 로직에서 인증 방식 변경
  src/main/java/com/back/domain/club/club/controller/ApiV1ClubController.java
  src/main/java/com/back/domain/club/club/service/ClubService.java
  src/main/java/com/back/domain/club/clubMember/controller/ApiV1ClubMemberController.java
  src/main/java/com/back/domain/club/clubMember/service/ClubMemberService.java
  src/main/java/com/back/global/security/SecurityConfig.java
  src/test/java/com/back/domain/club/club/controller/ApiV1ClubControllerTest.java
  src/test/java/com/back/domain/club/clubMember/controller/ApiV1ClubMemberControllerTest.java
Labels: refactor

#168 [Refactor] 프리셋 엔티티 수정
  src/main/java/com/back/domain/preset/preset/entity/Preset.java
Labels: refactor

#170 fix 시큐리티 설정
  src/main/java/com/back/global/security/SecurityConfig.java
  src/main/resources/application.yml
Labels: fix

#173 [Refactor] 일정 dto 추가 및 변경, 쿼리 변경
  src/main/java/com/back/domain/checkList/checkList/checker/CheckListAuthorizationChecker.java
  src/main/java/com/back/domain/checkList/checkList/dto/CheckListDto.java
  src/main/java/com/back/domain/schedule/schedule/checker/ScheduleAuthorizationChecker.java
  src/main/java/com/back/domain/schedule/schedule/controller/ApiV1ScheduleController.java
  src/main/java/com/back/domain/schedule/schedule/dto/request/ScheduleCreateReqBody.java
  src/main/java/com/back/domain/schedule/schedule/dto/request/ScheduleUpdateReqBody.java
  src/main/java/com/back/domain/schedule/schedule/dto/response/ScheduleDetailDto.java
  src/main/java/com/back/domain/schedule/schedule/dto/response/ScheduleDto.java
  src/main/java/com/back/domain/schedule/schedule/dto/response/ScheduleWithClubDto.java
  src/main/java/com/back/domain/schedule/schedule/repository/ScheduleRepository.java
  src/main/java/com/back/domain/schedule/schedule/service/ScheduleService.java
  src/test/java/com/back/domain/schedule/schedule/controller/ApiV1ScheduleControllerTest.java
Labels: refactor

#185 [hotfix] clubInfo 반환 리팩토링
  src/main/java/com/back/domain/club/club/service/ClubService.java
Labels: fix

#186 [hotfix] 모임 가입 신청 로직 수정
  src/main/java/com/back/domain/club/clubMember/service/MyClubService.java
Labels: fix

#187 [refactor] 매니저도 일정 생성, 삭제 가능하게 변경
  src/main/java/com/back/domain/schedule/schedule/controller/ApiV1ScheduleController.java
  src/test/java/com/back/domain/schedule/schedule/controller/ApiV1ScheduleControllerTest.java
Labels: refactor

#189 [refactor] 친구 목록 조회 시 요청dto 변경
  .gitignore
  src/main/java/com/back/domain/member/friend/controller/ApiV1FriendController.java
  src/main/java/com/back/domain/member/friend/dto/FriendDto.java
  src/main/java/com/back/domain/member/friend/dto/FriendStatusDto.java
  src/main/java/com/back/domain/member/friend/dto/FriendWithBioDto.java
  src/main/java/com/back/domain/member/friend/service/FriendService.java
  src/test/java/com/back/domain/member/friend/controller/ApiV1FriendControllerTest.java
Labels: refactor
