Repository DevCourse-KACG/Backend, pull requests merged in 2025-07, with the labels that each got.

#6 [chore] read.me 변경
  README.md
Labels: chore

#55 chore : 글로벌 클래스 설정
  build.gradle.kts
  src/main/java/com/back/global/app/AppConfig.java
  src/main/java/com/back/global/aspect/ResponseAspect.java
  src/main/java/com/back/global/exception/ServiceException.java
  src/main/java/com/back/global/globalExceptionHandler/GlobalExceptionHandler.java
  src/main/java/com/back/global/initData/DevInitData.java
  src/main/java/com/back/global/initData/TestInitData.java
  src/main/java/com/back/global/rq/Rq.java
  src/main/java/com/back/global/rsData/RsData.java
  src/main/java/com/back/global/security/CustomAuthenticationFilter.java
  src/main/java/com/back/global/security/CustomUserDetailsService.java
  src/main/java/com/back/global/security/SecurityConfig.java
  src/main/java/com/back/global/security/SecurityUser.java
  src/main/java/com/back/global/springDoc/SpringDocConfig.java
  src/main/java/com/back/global/webMvc/WebConfig.java
  src/main/java/com/back/standard/util/Ut.java
Labels: chore

#56 [chore] 기본 entity, repository 작성
  src/main/java/com/back/BackendApplication.java
  src/main/java/com/back/domain/checkList/checkList/entity/CheckList.java
  src/main/java/com/back/domain/checkList/checkList/entity/CheckListItem.java
  src/main/java/com/back/domain/checkList/checkList/repository/CheckListItemRepository.java
  src/main/java/com/back/domain/checkList/checkList/repository/CheckListRepository.java
  src/main/java/com/back/domain/checkList/itemAssign/entity/ItemAssign.java
  src/main/java/com/back/domain/checkList/itemAssign/repository/ItemAssignRepository.java
  src/main/java/com/back/domain/group/group/entity/Group.java
  src/main/java/com/back/domain/group/group/repository/GroupRepository.java
  src/main/java/com/back/domain/group/groupMember/entity/GroupMember.java
  src/main/java/com/back/domain/group/groupMember/repository/GroupMemberRepository.java
  src/main/java/com/back/domain/member/friend/entity/Friend.java
  src/main/java/com/back/domain/member/friend/entity/FriendStatus.java
  src/main/java/com/back/domain/member/friend/repository/FriendRepository.java
  src/main/java/com/back/domain/member/member/entity/Member.java
  src/main/java/com/back/domain/member/member/entity/MemberInfo.java
  src/main/java/com/back/domain/member/member/repository/MemberInfoRepository.java
  src/main/java/com/back/domain/member/member/repository/MemberRepository.java
  src/main/java/com/back/domain/preset/preset/entity/Preset.java
  src/main/java/com/back/domain/preset/preset/entity/PresetItem.java
  src/main/java/com/back/domain/preset/preset/repository/PresetItemRepository.java
  src/main/java/com/back/domain/preset/preset/repository/PresetRepository.java
  src/main/java/com/back/domain/schedule/schedule/entity/Schedule.java
  src/main/java/com/back/domain/schedule/schedule/repository/ScheduleRepository.java
  src/main/java/com/back/global/enums/CheckListItemCategory.java
  src/main/java/com/back/global/enums/GroupMemberRole.java
  src/main/java/com/back/global/enums/GroupMemberState.java
Labels: chore

#57 fix : 잘못된 부분 수정
  src/main/java/com/back/domain/member/member/entity/Member.java
Labels: fix

#59 [refactor] Group 관련 이름 변경
  src/main/java/com/back/domain/checkList/itemAssign/entity/ItemAssign.java
  src/main/java/com/back/domain/club/club/entity/Club.java
  src/main/java/com/back/domain/club/club/repository/ClubRepository.java
  src/main/java/com/back/domain/club/clubMember/entity/ClubMember.java
  src/main/java/com/back/domain/club/clubMember/repository/ClubMemberRepository.java
  src/main/java/com/back/domain/group/group/repository/GroupRepository.java
  src/main/java/com/back/domain/group/groupMember/repository/GroupMemberRepository.java
  src/main/java/com/back/domain/member/member/entity/Member.java
  src/main/java/com/back/domain/schedule/schedule/entity/Schedule.java
  src/main/java/com/back/global/enums/ClubMemberRole.java
  src/main/java/com/back/global/enums/ClubMemberState.java
  src/main/java/com/back/global/springDoc/SpringDocConfig.java
Labels: refactor

#60 [feat] 회원 가입 구현
  src/main/java/com/back/domain/api/service/ApiKeyService.java
  src/main/java/com/back/domain/auth/service/AuthService.java
  src/main/java/com/back/domain/member/member/MemberType.java
  src/main/java/com/back/domain/member/member/controller/ApiV1MemberController.java
  src/main/java/com/back/domain/member/member/dto/MemberDto.java
  src/main/java/com/back/domain/member/member/dto/MemberRegisterResponse.java
  src/main/java/com/back/domain/member/member/entity/Member.java
  src/main/java/com/back/domain/member/member/entity/MemberInfo.java
  src/main/java/com/back/domain/member/member/repository/MemberInfoRepository.java
  src/main/java/com/back/domain/member/member/repository/MemberRepository.java
  src/main/java/com/back/domain/member/member/service/MemberService.java
  src/main/java/com/back/global/config/jwt/JwtProperties.java
  src/main/resources/application.yml
  src/test/java/com/back/domain/member/member/ApiV1MemberControllerTest.java
  src/test/java/com/back/domain/member/member/MemberServiceTest.java
  src/test/java/support/MemberFixture.java
Labels: feat

#64 [feat] 일정 조회
  src/main/java/com/back/domain/schedule/schedule/controller/ApiV1ScheduleController.java
  src/main/java/com/back/domain/schedule/schedule/service/ScheduleService.java
  src/test/java/com/back/domain/schedule/schedule/controller/ApiV1ScheduleControllerTest.java
Labels: feat

#62 [feat] 모임 생성
  src/main/java/com/back/domain/club/club/controller/ApiV1ClubController.java
  src/main/java/com/back/domain/club/club/dtos/ClubControllerDtos.java
  src/main/java/com/back/domain/club/club/entity/Club.java
  src/main/java/com/back/domain/club/club/repository/ClubRepository.java
  src/main/java/com/back/domain/club/club/service/ClubService.java
  src/main/java/com/back/domain/club/clubMember/entity/ClubMember.java
  src/main/java/com/back/global/enums/ClubCategory.java
  src/main/java/com/back/global/enums/ClubMemberRole.java
  src/main/java/com/back/global/enums/EventType.java
  src/test/java/com/back/domain/club/club/controller/ApiV1ClubControllerTest.java
Labels: feat

#67 [Feat] 일정 삭제
  src/main/java/com/back/domain/checkList/checkList/entity/CheckList.java
  src/main/java/com/back/domain/schedule/schedule/controller/ApiV1ScheduleController.java
  src/main/java/com/back/domain/schedule/schedule/dto/ScheduleDto.java
  src/main/java/com/back/domain/schedule/schedule/entity/Schedule.java
  src/main/java/com/back/domain/schedule/schedule/service/ScheduleService.java
  src/main/java/com/back/global/initData/TestInitData.java
  src/test/java/com/back/domain/schedule/schedule/controller/ApiV1ScheduleControllerTest.java
Labels: feat

#68 [Feat] 프리셋 생성
  src/main/java/com/back/domain/checkList/checkList/entity/CheckListItem.java
  src/main/java/com/back/domain/preset/preset/controller/ApiV1PresetController.java
  src/main/java/com/back/domain/preset/preset/dto/PresetDto.java
  src/main/java/com/back/domain/preset/preset/dto/PresetItemDto.java
  src/main/java/com/back/domain/preset/preset/dto/PresetItemWriteReqDto.java
  src/main/java/com/back/domain/preset/preset/dto/PresetWriteReqDto.java
  src/main/java/com/back/domain/preset/preset/entity/Preset.java
  src/main/java/com/back/domain/preset/preset/entity/PresetItem.java
  src/main/java/com/back/domain/preset/preset/service/PresetService.java
  src/test/java/com/back/domain/preset/ApiV1PresetControllerTest.java
Labels: feat

#72 [Feat] 프리셋 세부 정보 조회
  src/main/java/com/back/domain/preset/preset/controller/ApiV1PresetController.java
  src/main/java/com/back/domain/preset/preset/service/PresetService.java
  src/test/java/com/back/domain/preset/ApiV1PresetControllerTest.java
Labels: feat

#69 [Feat] 일정 목록 조회
  src/main/java/com/back/domain/schedule/schedule/controller/ApiV1ScheduleController.java
  src/main/java/com/back/domain/schedule/schedule/entity/Schedule.java
  src/main/java/com/back/domain/schedule/schedule/repository/ScheduleRepository.java
  src/main/java/com/back/domain/schedule/schedule/service/ScheduleService.java
  src/main/java/com/back/global/initData/TestInitData.java
  src/test/java/com/back/domain/schedule/schedule/controller/ApiV1ScheduleControllerTest.java
Labels: feat

#82 [hotfix] autoPR workflow 수정
  .github/workflows/autoPR.yml
Labels: fix

#84 [feat] 모임 소개 - 누구나
  src/main/java/com/back/domain/club/club/controller/ApiV1ClubController.java
  src/main/java/com/back/domain/club/club/dtos/ClubControllerDtos.java
  src/main/java/com/back/domain/club/club/service/ClubService.java
  src/main/java/com/back/domain/member/member/service/MemberService.java
  src/test/java/com/back/domain/club/club/controller/ApiV1ClubControllerTest.java
Labels: feat

#85 [feat] 모임 상세 - 참여자만
  src/main/java/com/back/domain/club/club/controller/ApiV1ClubController.java
  src/main/java/com/back/domain/club/club/dtos/ClubControllerDtos.java
  src/main/java/com/back/domain/club/club/service/ClubService.java
  src/test/java/com/back/domain/club/club/controller/ApiV1ClubControllerTest.java
Labels: feat

#83 [Feat] : 프리셋 수정
  src/main/java/com/back/domain/club/club/dtos/ClubControllerDtos.java
  src/main/java/com/back/domain/club/club/service/ClubService.java
  src/main/java/com/back/domain/preset/preset/controller/ApiV1PresetController.java
  src/main/java/com/back/domain/preset/preset/entity/Preset.java
  src/main/java/com/back/domain/preset/preset/service/PresetService.java
  src/test/java/com/back/domain/preset/ApiV1PresetControllerTest.java
Labels: feat

#88 [feat] 공개 모임 목록 조회
  src/main/java/com/back/domain/club/club/controller/ApiV1ClubController.java
  src/main/java/com/back/domain/club/club/dtos/ClubControllerDtos.java
  src/main/java/com/back/domain/club/club/repository/ClubRepository.java
  src/main/java/com/back/domain/club/club/service/ClubService.java
  src/test/java/com/back/domain/club/club/controller/ApiV1ClubControllerTest.java
Labels: feat

#90 [feat] Access token 재발급
  src/main/java/com/back/domain/api/dto/TokenRefreshRequest.java
  src/main/java/com/back/domain/member/member/controller/ApiV1MemberController.java
  src/main/java/com/back/domain/member/member/repository/MemberInfoRepository.java
  src/main/java/com/back/domain/member/member/service/MemberService.java
  src/test/java/com/back/domain/member/member/ApiV1MemberControllerTest.java
Labels: feat

#93 [feat] 비밀번호 인증
  src/main/java/com/back/domain/member/member/controller/ApiV1MemberController.java
  src/main/java/com/back/domain/member/member/dto/request/PasswordCheckRequestDto.java
  src/main/java/com/back/domain/member/member/dto/response/MemberPasswordResponse.java
  src/main/java/com/back/domain/member/member/service/MemberService.java
  src/test/java/com/back/domain/member/member/ApiV1MemberControllerTest.java
Labels: feat

#94 [Feat] 친구 추가
  src/main/java/com/back/domain/member/friend/controller/ApiV1FriendController.java
  src/main/java/com/back/domain/member/friend/dto/FriendAddReqBody.java
  src/main/java/com/back/domain/member/friend/dto/FriendDto.java
  src/main/java/com/back/domain/member/friend/entity/Friend.java
  src/main/java/com/back/domain/member/friend/repository/FriendRepository.java
  src/main/java/com/back/domain/member/friend/service/FriendService.java
  src/main/java/com/back/domain/member/member/repository/MemberInfoRepository.java
  src/main/java/com/back/domain/schedule/schedule/controller/ApiV1ScheduleController.java
  src/main/java/com/back/global/globalExceptionHandler/GlobalExceptionHandler.java
  src/main/java/com/back/global/initData/TestInitData.java
  src/test/java/com/back/domain/member/friend/controller/ApiV1FriendControllerTest.java
  src/test/java/com/back/domain/schedule/schedule/controller/ApiV1ScheduleControllerTest.java
Labels: feat

#95 [feat] 내 정보 수정
  src/main/java/com/back/domain/member/member/controller/ApiV1MemberController.java
  src/main/java/com/back/domain/member/member/dto/request/UpdateMemberInfoDto.java
  src/main/java/com/back/domain/member/member/entity/Member.java
  src/main/java/com/back/domain/member/member/entity/MemberInfo.java
  src/main/java/com/back/domain/member/member/service/MemberService.java
  src/test/java/com/back/domain/member/member/ApiV1MemberControllerTest.java
Labels: feat

#96 [feat] 참여자 추가
  src/main/java/com/back/domain/club/club/controller/ApiV1ClubController.java
  src/main/java/com/back/domain/club/clubMember/controller/ApiV1ClubMemberController.java
  src/main/java/com/back/domain/club/clubMember/dtos/ClubMemberDtos.java
  src/main/java/com/back/domain/club/clubMember/repository/ClubMemberRepository.java
  src/main/java/com/back/domain/club/clubMember/service/ClubMemberService.java
  src/main/java/com/back/domain/member/member/entity/Member.java
  src/main/java/com/back/global/initData/TestInitData.java
  src/test/java/com/back/domain/club/club/controller/ApiV1ClubControllerTest.java
  src/test/java/com/back/domain/club/clubMember/controller/ApiV1ClubMemberControllerTest.java
Labels: feat

#101 [feat] 참여자 삭제
  src/main/java/com/back/domain/club/clubMember/controller/ApiV1ClubMemberController.java
  src/main/java/com/back/domain/club/clubMember/entity/ClubMember.java
  src/main/java/com/back/domain/club/clubMember/repository/ClubMemberRepository.java
  src/main/java/com/back/domain/club/clubMember/service/ClubMemberService.java
  src/main/java/com/back/global/rq/Rq.java
  src/test/java/com/back/domain/club/clubMember/controller/ApiV1ClubMemberControllerTest.java
Labels: feat

#102 [feat] 친구 수락
  src/main/java/com/back/domain/member/friend/controller/ApiV1FriendController.java
  src/main/java/com/back/domain/member/friend/service/FriendService.java
  src/test/java/com/back/domain/member/friend/controller/ApiV1FriendControllerTest.java
Labels: feat

#104 [Feat] 체크리스트 생성
  src/main/java/com/back/domain/checkList/checkList/controller/ApiV1CheckListController.java
  src/main/java/com/back/domain/checkList/checkList/dto/CheckListDto.java
  src/main/java/com/back/domain/checkList/checkList/dto/CheckListItemDto.java
  src/main/java/com/back/domain/checkList/checkList/dto/CheckListItemWriteReqDto.java
  src/main/java/com/back/domain/checkList/checkList/dto/CheckListWriteReqDto.java
  src/main/java/com/back/domain/checkList/checkList/entity/CheckList.java
  src/main/java/com/back/domain/checkList/checkList/entity/CheckListItem.java
  src/main/java/com/back/domain/checkList/checkList/service/CheckListService.java
  src/main/java/com/back/domain/checkList/itemAssign/dto/ItemAssignDto.java
  src/main/java/com/back/domain/checkList/itemAssign/dto/ItemAssignReqDto.java
  src/main/java/com/back/domain/checkList/itemAssign/entity/ItemAssign.java
  src/main/java/com/back/domain/preset/preset/controller/ApiV1PresetController.java
  src/main/java/com/back/domain/preset/preset/service/PresetService.java
  src/main/java/com/back/domain/schedule/schedule/entity/Schedule.java
  src/test/java/com/back/domain/checkList/ApiV1CheckListControllerTest.java
  src/test/java/com/back/domain/preset/ApiV1PresetControllerTest.java
Labels: feat

#106 [Feat] 친구 요청 거절
  src/main/java/com/back/domain/member/friend/controller/ApiV1FriendController.java
  src/main/java/com/back/domain/member/friend/service/FriendService.java
  src/test/java/com/back/domain/member/friend/controller/ApiV1FriendControllerTest.java
Labels: feat

#109 [feat] 참여자 목록 조회
  src/main/java/com/back/domain/club/clubMember/controller/ApiV1ClubMemberController.java
  src/main/java/com/back/domain/club/clubMember/dtos/ClubMemberDtos.java
  src/main/java/com/back/domain/club/clubMember/repository/ClubMemberRepository.java
  src/main/java/com/back/domain/club/clubMember/service/ClubMemberService.java
  src/main/java/com/back/global/initData/TestInitData.java
  src/test/java/com/back/domain/club/clubMember/controller/ApiV1ClubMemberControllerTest.java
Labels: feat

#111 [hotfix] 테스트 오류 수정
  src/test/java/com/back/domain/member/member/ApiV1MemberControllerTest.java
Labels: fix

#112 [Refactor] 멤버 컨트롤러 리팩토링
  src/main/java/com/back/domain/auth/service/AuthService.java
  src/main/java/com/back/domain/club/club/service/ClubService.java
  src/main/java/com/back/domain/club/clubMember/service/ClubMemberService.java
  src/main/java/com/back/domain/member/member/controller/ApiV1MemberController.java
  src/main/java/com/back/domain/member/member/dto/request/CustomMemberDto.java
  src/main/java/com/back/domain/member/member/service/MemberService.java
  src/main/java/com/back/global/security/CustomAuthenticationFilter.java
  src/main/java/com/back/global/security/CustomUserDetailsService.java
  src/main/java/com/back/global/security/SecurityUser.java
  src/test/java/com/back/domain/club/club/controller/ApiV1ClubControllerTest.java
  src/test/java/com/back/domain/club/clubMember/controller/ApiV1ClubMemberControllerTest.java
  src/test/java/com/back/domain/member/member/ApiV1MemberControllerTest.java
  src/test/java/com/back/domain/member/member/MemberServiceTest.java
  src/test/java/com/back/domain/member/member/support/MemberFixture.java
Labels: refactor

#119 [feat] getActor 구현
  src/main/java/com/back/domain/member/member/controller/ApiV1MemberController.java
  src/main/java/com/back/domain/member/member/entity/Member.java
  src/main/java/com/back/global/rq/Rq.java
Labels: feat

#122 [Feat] 멤버 테스트 케이스 추가
  src/main/java/com/back/domain/auth/service/AuthService.java
  src/main/java/com/back/domain/club/clubMember/dtos/ClubMemberDtos.java
  src/main/java/com/back/domain/member/member/dto/request/MemberLoginDto.java
  src/main/java/com/back/domain/member/member/dto/request/MemberRegisterDto.java
  src/main/java/com/back/domain/member/member/entity/Member.java
  src/main/java/com/back/domain/member/member/service/MemberService.java
  src/main/java/com/back/global/enums/MemberType.java
  src/main/java/com/back/global/globalExceptionHandler/GlobalExceptionHandler.java
  src/main/java/com/back/global/initData/TestInitData.java
  src/main/java/com/back/global/security/SecurityUser.java
  src/test/java/com/back/domain/club/clubMember/controller/ApiV1ClubMemberControllerTest.java
  src/test/java/com/back/domain/member/member/ApiV1MemberControllerTest.java
Labels: feat

#133 [feat] 모임 초대 수락
  src/main/java/com/back/domain/club/clubMember/controller/ApiV1ClubMemberController.java
  src/main/java/com/back/domain/club/clubMember/controller/ApiV1MyClubController.java
  src/main/java/com/back/domain/club/clubMember/dtos/MyClubControllerDtos.java
  src/main/java/com/back/domain/club/clubMember/service/MyClubService.java
  src/test/java/com/back/domain/club/clubMember/controller/ApiV1MyClubControllerTest.java
Labels: feat
